FUNCTION "_compareWithTolerance" : Void
TITLE = {"status":"current","deprecatedBy": null,"dependencies" : []}
{ S7_Optimized_Access := 'TRUE' }
AUTHOR : cyanezf
FAMILY : 'core/control/util'
NAME : _compareWithTolerance
VERSION : 1.0

   VAR_INPUT 
      a : LReal;   // Value A
      b : LReal;   // Value B
      tolerance : LReal;   // Tolerance (>= and <=)
   END_VAR


BEGIN
(*--
# Documentation

## Log

| version | date | author | description |
|:-------:|:----:|:------:|:------------|
| v1.0 | 2025-01-10 | cyanezf | First version |

## Description

This function compares `a` and `b` are equales with a `tolerance`.

--*)

	// Save RLO
	ENO := ABS(#a - #b) <= #tolerance;
		
END_FUNCTION

